### ISSUE TITLE
Summarize section

### ISSUE THREAD

**Issue by brunj7** [NCEAS/scicomp-workshop-tidyverse#3]
Looks great, 2 suggestions:
- add the hex sticker of `magrittr` to support the fun fact
- Maybe do a simplier `summarize` first, then the one with several computations at the same time

**Comment by njlyon0** [comment]
Great feedback, thanks! Implemented here: https://github.com/NCEAS/scicomp-workshop-tidyverse/commit/ec32f20a3e98992318cd8945da81647d8274aacb
