### ISSUE TITLE
Join section

### ISSUE THREAD

**Issue by brunj7** [NCEAS/scicomp-workshop-tidyverse#4]
Looks good!

Suggestion:
- Switch `head()` for `glimpse()` so you can show row and column numbers
- Maybe add an example where you filter the left dataset first so you can show that the number of rows of the output dataset is always the left one on a `left_join()`

**Comment by njlyon0** [comment]
Edits implemented here: https://github.com/NCEAS/scicomp-workshop-tidyverse/commit/a5d331829fbc7f64607b3135202cb7d3158f4129

Thanks!
